//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameGameDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public int UserId { get; set; }
        public string GameMode { get; set; }
        public string GameData { get; set; }
        public int QCount { get; set; }
        public int QAttempts { get; set; }
        public int QCompleted { get; set; }
        public string QAnswers { get; set; }
        public string QClues { get; set; }
    }
}
