//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameGameDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStat
    {
        public int StatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CorrectAttempts { get; set; }
        public Nullable<int> IncorrectAttempts { get; set; }
        public Nullable<int> QuestionsPresented { get; set; }
        public Nullable<int> TimeInGame { get; set; }
    }
}
